pupnp/pupnp

upnp/src/api/upnpdebug.c
- If the error or info log files can not be created, use stderr and
stdout instead.
=> Fix crash when debug is enabled

ixml/Makefile.am, ixml/test/test_document.sh, upnp/Makefile.am, upnp/sample/Makefile.am, upnp/unittest/Makefile.am
Update names of sample, test and unittest programs of 1.8.x branch to
avoid any collision with the programs of the "usual" 1.6.x branch
Rename:
- tv_ctrlpt in tv_ctrlpt-1.8
- tv_combo in tv_combo-1.8
- tv_device in tv_device-1.8
- unittest in unittest-1.8
- test_init in test_init-1.8
- test_url in test_url-1.8
- test_document in test_document-1.8
Signed-off-by: Fabrice Fontaine <fabrice.fontaine@orange.com>
=> Update sample, test and unittest program names

build/inc/autoconfig.h, configure.ac, threadutil/Makefile.am
The define is never used anywhere.
=> Remove NO_DEBUG define

ixml/src/ixmlparser.c
Even though the LFS defines (like `_FILE_OFFSET_BITS`) are setup, some parts of libixml were not using them because `autoconfig.h` had not been included.
=> Use LFS functions in libixml

configure.ac, upnp/src/genlib/miniserver/miniserver.c
This adds a compile time option "--enable-reuseaddr" which enables the
previously unavailable SO_REUSEADDR codepath in miniserver.c
This allows us the normal advantages of REUSEADDR when implementing
servers that would like graceful restarts.
See v00d00/mediatomb#34
=> Add option to use REUSEADDR on miniserver socket

ChangeLog, configure.ac, upnp/src/inc/md5.h, upnp/src/uuid/md5.c
Currently the RSA MD5 implementation is used. Unfortunately the license has some potential issues:
* The license does not explicitly allow distributing derivative works. This was the original argument used in [Debian #459516](https://bugs.debian.org/459516).
* The license contains an advertising clause similar to the BSD 4-clause license. This is incompatible with the GPL and if it were enforced, would require RSA to be mentioned by pretty much everyone who uses pupnp.
The simple solution is to replace it with a public domain implementation. I've taken OpenBSDs implementation and tweaked it slightly for use by pupnp.
=> Replace MD5 impmplementation with a public-domain version

upnp/inc/upnpconfig.h.in
I missed this as part of the inital PR.
Useful for consumers to be able to test fot the behaviour change at build time.
Also unifies the spacing between items to a single newline.
=> Expose reuseaddr status in upnpconfig.h

Makefile.am
a blank line can not follow a trailing backslash
=> Fix syntax error in Makefile.am EXTRA_DIST introduced by b4a9ac0ddf212c7cd081fb62e0a101628ff0e6d2

upnp/src/api/upnpdebug.c, upnp/src/inc/upnpapi.h
This change makes libupnp debug messages appear in a more traditional
log format, example below:
```
2017-06-07 22:22:42 UPNP: Thread:0x7F8085807700 [src/ssdp/ssdp_server.c:440]: Exiting AdvertiseAndReply.
2017-06-07 22:22:42 UPNP: Thread:0x7F8084805700 [src/ssdp/ssdp_ctrlpt.c:106]: Trying a read lock
```
This is makes it much easier to see what is going on, especially when
multiple things are happening, and includes the date/time for
correlation.
- Change the output file names to "libupnp_err.log" and "libupnp_info.log"
which more clearly describe their purpose.
- Fix the inverted check for DEBUG and write to stdout as expected.
- Fix some missing newlines in the lock logging.
=> Simplify logging format

configure.ac, upnp/src/api/upnpapi.c, upnp/src/gena/gena_device.c, upnp/src/genlib/net/http/httpreadwrite.c, upnp/src/genlib/service_table/service_table.c, upnp/src/inc/config.h, upnp/src/inc/gena.h, upnp/src/inc/service_table.h, upnp/src/inc/upnpapi.h
Add possibility to discard events destined to non-responding control point based on event age, in addition to maximum queue lenth.
- Delete eventKey field from event data structure: it was set but never used.
- Add ctime age field.
- Add max age configuration parameter.
- Define function for setting max queue size and max event age, in the case where compiled-in defaults are not appropriate.
=> Device eventing: add possibility to discard events based on age

upnp/inc/upnp.h, upnp/src/genlib/net/http/httpreadwrite.c, upnp/src/genlib/net/http/webserver.c
Allow extra headers to be sent to client in the File_Info struct by adding extra_headers, an array of struct Extra_Headers.
It contains "name" and "value" and the callee can populate a DOMString "resp" to add a header as well in the reponse
=> extra headers

upnp/src/api/upnpapi.c
If any of the address families isn't available in `UpnpGetIfInfo()`, especially
IPv6, always init both structs with zero to avoid garbage output with
`inet_ntop()` to `gIF_IPV4` and `gIF_IPV6`.
See v00d00/gerbera#112 for consequences: bind for IPv6 will fail.
=> Initialize in_addr and in6_addr to avoid garbage output if never written

upnp/inc/upnp.h, upnp/src/api/upnpapi.c, upnp/src/genlib/net/http/httpreadwrite.c, upnp/src/genlib/net/http/webserver.c, upnp/src/inc/VirtualDir.h, upnp/src/inc/webserver.h
As with the main Device APIs (UpnpRegisterRootDevice etc), it is useful to
have a userdata/cookie pointer returned with each callback.
This patch allows one cookie per registered path which enables a variety of
functionality in client apps
=> Add userdata/cookie to virtualDir callbacks

upnp/src/genlib/net/http/httpreadwrite.c
When upmpdcli is linked with libupnp 1.6.24 it aborts with an segmentation fault, but linking with libupnp workes just fine.
git bisect shows that commit 9c2e8ec8a0291ebe81959009e2f78edbdb47ced5 is the bad one as the variable `extras` is not properly checked before attempting to used it as a pointer.
Asure `extras` is not Null before using it.
=> Fix segmentation fault in http_MakeMessage

libupnp.pc.in
while discussing with MPD upstream it was pointed out that `-pthread` isn't necessary in the output of `pkg-config --cflags libupnp`. 
Other than that it strikes me that `@PTHREAD_CFLAGS@` is used in the `Libs:` line and I wonder if this is correct. (For static linking `-pthread` is needed even for single threaded consumers. And it seems it doesn't need to be at the end to get it in the right linking order while the order of `-lupnp -lthreadutil -lixml` matters.) Will think about this for a while ...
=> libupnp.pc: drop -pthread from Cflags

upnp/src/genlib/net/http/httpreadwrite.c
@philippe44
An assert(0) is hit if fmt contains a char that is not expected. Support
for 'E' was added without making sure that this assert isn't reached.
This only hurts in debug builds and so shows that nobody tests these :-)
Fixes: 9c2e8ec8a029 ("extra headers")
Reported-by: Tobias Frost <tobi@coldtobi.de>
=> Fix assertion error when http_MakeMessage is called with E in fmt

upnp/inc/upnp.h
Now after starting to convert some programs to libupnp 1.8 I noticed
some defines to be missing and some others to be wrong. Fix that.
Fixes: 8177a4195a4d ("Add some compat helpers")
=> Fix and add more compat helpers

upnp/inc/upnp.h
With these I was able to create a patch that allows to compile
amule with both libupnp 1.6 and libupnp 1.8.
=> Some more compat helpers

Makefile.am
Given that the .tar.bz2 provided on sf.net has some local changes introduce a check to the dist
target that makes this a tad harder.
=> Ensure there are no uncommitted changes when creating tar balls

upnp/src/genlib/net/http/httpreadwrite.c
Many Samsung DTVs will not recognize UPnP/DLNA media servers, because they are picky about HTTP imlementation. E.g. they loop until double CRLF is found after HTTP header. If not found, then there is no processing done. -> connection failed.
A snippet out of B series TV:
`
.text:0145DCF0 0A 00 A0 E1 MOV R0, R10 ; haystack
.text:0145DCF4 E8 12 9F E5 LDR R1, =asc_215F5E0 ; "\r\n\r\n"
.text:0145DCF8 52 4C C3 EB BL strstr
.text:0145DCFC 00 00 50 E3 CMP R0, #0
.text:0145DD00 E1 FF FF 0A BEQ loc_145DC8C ; loop until EOF found
.text:0145DD04 0A 00 A0 E1 MOV R0, R10
.text:0145DD08 1F FF FF EB BL _Z15cpParseHTTPRespPc ; cpParseHTTPResp(char *)
`
In addition they send "HTTP/1.0" requests, which need to be handled properly, too.
The proposed patch fixes mentioned issues.
The patch was discussed …
=> Fix handling of http header processing for better operability with Samsung DTVs

upnp/src/genlib/net/http/httpreadwrite.c
I checked that the issue existed on 32 bits system, and that the proposed fix did correct it. I guess that the pull request mentionned in the request is not coming, so here it is.
=> Webserver: avoid casting total  size from off_t to size_t when reading a file. Fixes issue #81

upnp/src/genlib/net/http/httpreadwrite.c
Can't understand why I don't get the warnings, tried gcc and clang. Hopefully, adding the explicit casts should silence them.
=> Added a number of explicit casts to avoid compiler warnings

upnp/inc/upnp.h
These are necessary to compile gmrender-resurrect after converting it
to compile with libupnp-1.8.
=> Another set of compat helpers for libupnp-1.6

upnp/src/genlib/miniserver/miniserver.c
Fixes issue #91
If the UPNP_MINISERVER_REUSEADDR option is active, set SO_REUSEADDR on the
socket, but then proceed to loop on busy ports until we find a free one
(using the existing code from the non-reuseaddr case). This allows a single
instance of libupnp to always use the same port, even immediately after a
restart, but also allows multiple instances to use different ports without
need for explicit configuration.
The change is simpler than it appears in the diff: I just remove the bind() calls from the reuseaddr optional branch, and fallthrough to the default looping code (by removing the else {}). 
Indentation changes make it appear bigger than it is.
=> Use higher port when reuseaddr is set and the default port is busy

.gitignore, configure.ac, upnp/sample/common/config_sample.h.in, upnp/sample/common/sample_util.h
Create a configuration file specific to the samples, to mimick what a
regular application would have to do.
Fixes #94
=> Ensure that the samples use the same largefile options as the library

upnp/Makefile.am, upnp/inc/upnpdebug.h, upnp/src/api/upnpapi.c, upnp/src/api/upnpdebug.c, upnp/src/genlib/net/http/httpparser.c, upnp/src/genlib/net/http/httpreadwrite.c, upnp/src/genlib/net/uri/uri.c, upnp/src/ssdp/ssdp_device.c, upnp/src/threadutil/ThreadPool.c, upnp/test/test_log.c
- Create no files and write nothing by default.
- Accept any sequence of init/close/print without crashing or leaking
resources.
- Never ever write anything to stdout, the app may use it.
- Use a single file with enough data in each message to enable filtering.
- Minimum change to the message format (add level and target), in a way
unlikely to confuse a hypothetical existing parser.
- No change to the API, except that:
* the 2nd file name parameter to UpnpSetLogFilenames is ignored.
* DebugAtThisLevel is gone from the include file (not exported and not
used internally anyway)
* UpnpDisplayFileAndLine() and UpnpDisplayBanner() are gone.
- Also replace some fprintf() calls with upnpprintf() (httpparser.c)
=> Clean up the log module.

upnp/inc/upnp.h, upnp/src/genlib/net/http/httpreadwrite.c, upnp/src/genlib/net/http/webserver.c, upnp/src/inc/httpreadwrite.h, upnp/src/inc/webserver.h
Currently there is no mechanism inside libupnp to track data accross the `get_info` -> `read` ->` close` flow of VirtualDir calls.
This means that client applications may have to do operations such as parsing and access checks etc twice, once in get_info, and again in read, or somehow track request lifetimes.
This change adds a new argument to the VirtualDir callbacks, so is not backwards compatible.
=> Add Request level cookies to virtualdir calls

configure.ac, libupnp.pc.in
- Add a call to PKG_CHECK_MODULES to get openssl libraries and its
dependencies if openssl support is enabled
- Add OPENSSL_LIBS to libupnp.pc.in so that applications linking with
pupnp (such as mpd) will be able to retrieve openssl libraries
Fixes:
- http://autobuild.buildroot.org/results/a4148e516070b79816769f3443fc24d6d8192073
=> configure.ac: fix build with openssl

libupnp.pc.in
openssl is a private library so move it from Libs to Libs.private
in libupnp.pc.in
=> libupnp.pc.in: move openssl in Libs.private

ixml/src/ixmlparser.c
when c is large enough, m can become equal to sz (found with AFL).
=> fix off-by-one overread on global variable

upnp/sample/common/sample_util.c
this avoids a crash when the first child node has an empty value
found with AFL
=> check strdup argument against NULL

upnp/sample/common/sample_util.c, upnp/sample/common/tv_ctrlpt.c
UpnpResolveURL is a tricky API to use correctly and the samples
allocate one bytes less than strictly required. This code has
been copied into other applications that similarly have problems
alocating the correct amount of space. Fortunately UpnpResolveURL2
is available and it avoids the need to allocate space in the caller
and does less copying too.
=> upnp/sample: Use UpnpResolveURL2 in samples

upnp/src/genlib/net/http/webserver.c, upnp/src/inc/webserver.h
As the subject says. The callback cookie parameters in struct SendInstruction were not always zeroed on initialization. As usual, it was probably not a problem, until it would become one.
=> Always fully initialize struct SendInstruction. Fix indentation in webserver.h

upnp/src/inc/config.h
The DEBUG_TARGET is no longer used, it was previously used in
upnpdebug.c to disable logging to a file, which now is done
by just not calling UpnpSetLogFileNames.
=> config.h: Remove DEBUG_TARGET

upnp/src/api/upnpapi.c
The mentioned fix is not only needed for MSVC, but when
cross-compiling for Windows with mingw-w64 too.
=> Fix interface filtering for Windows

upnp/Makefile.am, upnp/inc/TemplateInclude.h, upnp/inc/TemplateSource.h, upnp/src/genlib/net/http/httpreadwrite.c, upnp/src/genlib/net/http/webserver.c, upnp/src/genlib/util/list.c
This is an example of replacing the current list.h 
The list interface is modeled on std::list (a small subset, adapted for c).
I have not tested the implementation with actual extraheaders, I am having trouble building Gerbera
No more macros, but we have to export the list interface routines.
I think that this is much easier to understand than the previous, but this is also a question of taste...
=> Remove and replace the list.h file

upnp/inc/list.h
The list.h functions need to be properly exported on Windows.
=> Add forgotten Windows dll export qualifiers

upnp/src/inc/uri.h
These defines are no longer used anywhere.
=> Remove unused defines in uri.h

upnp/inc/upnp.h, upnp/src/api/upnpapi.c
Return UPNP_E_NO_WEB_SERVER when webs erver was compiled-out, as then
it is impossible to enable/disable it.
=> UpnpEnableWebserver: Error correctly when web server compiled-out

upnp/src/genlib/net/http/webserver.c
I (re)discovered this behavior trying to use the Gerbera media server
with Chromecast (built in to my Vizio P55-F1 TV).  Chromecast specifies
"bytes:0-" with no end range, which caused pupnp to return
RANGE_NOT_SATISFIABLE.  Jin, the author of MediaTomb, of which Gerbera
is a continuation, fixed this in 2007 in MediaTomb's fork of pupnp, see
gerbera@ccd7994d45 "made sure that range requests specified as
"bytes=0-" do not trigger...", but never passed the fix upstream.  When
restarted as Gerbera, pupnp was removed from the local tree in favor of
using the upstream version, and the patch was lost which lead to me
rediscovering it recently.
This is Jin's original patch applied to pupnp 1.8.  This teaches punp to
ignore the bytes header if it matches "0-" and return HTTP_OK.
=> Reduce spurious HTTP 416 errors due to ill-defined bytes header

upnp/inc/FileInfo.h, upnp/src/genlib/net/http/webserver.c
Similar to UpnpActionRequest class add  CtrlPtIPAddr member. This implementation is mostly a copy/paste from UpnpActionRequest path.
This information can later be used by devices (Gerbera https://github.com/gerbera/gerbera) to inject client (e.g. SamsungTV) specific quirks. Like extra headers, special mime types, etc...
=> add CtrlPtIPAddr to UpnpFileInfo class

upnp/inc/ActionRequest.h, upnp/inc/FileInfo.h, upnp/src/genlib/net/http/webserver.c, upnp/src/soap/soap_device.c
Similar to UpnpDiscovery class add Os member. This implementation is mostly a copy/paste from UpnpDiscovery path, except that i do only look for "USER-AGENT" and not the "SERVER" header entry, as i think the "SERVER" part makes no sense for those "client to server" requests. 
This will give us more flexibility in Gerbera (https://github.com/gerbera/gerbera) when applying quirks.
With this information we can directly use the "USER-AGENT" implementation. For devices where "USER-AGENT" is not good enough, we can use the discovery/CtrlPtIPAddr path.
Works like a charm for VLC + BubbleUPnP
=> add Os/UserAgent information to UpnpActionRequest and UpnpFileInfo

upnp/inc/ithread.h, upnp/src/genlib/miniserver/miniserver.c
usleep is deprecated and is optionally unavailable with uClibc-ng.
Signed-off-by: Rosen Penev <rosenp@gmail.com>
=> Do not use usleep when using newer POSIX C source.

upnp/inc/ithread.h, upnp/src/genlib/miniserver/miniserver.c
usleep is deprecated and is optionally unavailable with uClibc-ng.
Signed-off-by: Rosen Penev <rosenp@gmail.com>
(cherry picked from commit c91d82a7b74df3a08de2f94a1ec2a75a7803b6bd)
Version 1.8 is used in OpenWrt as later versions cause some incompatibility problems.
=> [1.8.x]Do not use usleep when using newer POSIX C source.

upnp/inc/ithread.h, upnp/src/genlib/miniserver/miniserver.c
usleep is deprecated and is optionally unavailable with uClibc-ng.
Signed-off-by: Rosen Penev <rosenp@gmail.com>
(cherry picked from commit c91d82a7b74df3a08de2f94a1ec2a75a7803b6bd)
=> [1.10.x]Do not use usleep when using newer POSIX C source.

upnp/src/genlib/net/http/httpparser.c
Original patch:
https://sourceforge.net/p/mediatomb/code/ci/2753e70013636bb5dd4cfc595f9776d368709f04/tree/tombupnp/upnp/src/genlib/net/uri/uri.c?diff=6be2b0d6e512fd60f155acf78b1f7c1725f58571
This patch is needed for "Samsung Smart TV 2012" and older. ~~But it also makes `parse_uri` more robust for everybody:~~
- ~~the schema should only be looked at when we found a schema at all~~
- ~~multiple slashes in URLs are actually allowed and can happen~~
Parse `GET \\cm.xml` to:
- Method = GET
- URL = `\cm.xml` instead of `\\cm.xml`
=> backport mediatomb fix, but place it in httpparser

upnp/src/threadutil/ThreadPool.c
Add libupnp prefix and function name for easier recognizability, this message
usually end up mixed in logs of other applications using libupnp.
Add missing new line to avoid mangling other log messages.
=> Improve traceability of debug message in ThreadPool

upnp/src/api/upnpapi.c, upnp/src/gena/gena_device.c, upnp/src/inc/upnpapi.h
This is a partial fix for CallStranger a.k.a. CVE-2020-12695
Check that DeliveryURLs are in the expected network segment as requested
by the new UPnP UDA:
https://openconnectivity.org/upnp-specs/UPnP-arch-DeviceArchitecture-v2.0-20200417.pdf.
Here is an extract of the new requirement:
The subscription request containing a delivery URL not on the same
network segment as the fully qualified event subscription URL shall not
be accepted. For private networks this means that the delivery URL
provided will adhere to the following IP ranges:
- 10.0.0.0 - 10.255.255.255 (10/8 prefix)
- 172.16.0.0 - 172.31.255.255 (172.16/12 prefix)
- 192.168.0.0 - 192.168.255.255 (192.168/16 prefix)
In the context of pupnp, this means that the IPv4 netmask is now
retrieved when using UPnPInit2. Then, each …
=> Partial fix for CallStranger on IPv4

upnp/src/api/upnpapi.c
BSD is using getifaddrs, update the code to retrieve the IPv4 netmask
(used in the CallStranger fix)
=> upnpapic.c: retrieve gIF_IPV4_NETMASK with BSD

upnp/inc/upnp.h, upnp/sample/common/tv_device.c, upnp/sample/common/tv_device.h, upnp/src/api/upnpapi.c, upnp/src/genlib/miniserver/miniserver.c, upnp/src/inc/miniserver.h
Currently, the miniserver only listens on the link local `gIF_IPV6`
address, this is an issue as the link local address is only available on
the current link (e.g. Ethernet) and not on the IPv6 "LAN". In other
words, this IPv6 address is not reachable if there is a router between
the UPnP device and the UPnP Control Point (which is the case for most
of our users).
So open a socket for `gIF_IPV6_ULA_GUA` to allow a device to call
`UpnpRegisterRootDevice3` or `UpnpRegisterRootDevice4` with the following
DescUrl:
```
sprintf(descDocUrlUlaGua, "http://[%s]:%d/%s", UpnpGetServerUlaGuaIp6Address(),
UpnpGetServerUlaGuaPort6(), g_vars.descDocName);
```
Also add a new `UpnpGetServerUlaGuaPort6` function to retrieve the port
for this ULA or GUA address (as it can be different from …
=> Allow the miniserver to listen on ULA or GUA IPv6 address

upnp/src/api/upnpapi.c, upnp/src/gena/gena_device.c, upnp/src/inc/upnpapi.h
Retrieve IPv6 prefix for LLA or ULA/GUA and use it instead of IPv4
netmask
=> Fix CallStranger on IPv6

upnp/src/genlib/miniserver/miniserver.c
When adding management of IPV6 ULA/GUA in commit
9d58b9c537b38c72d1aeb968d775410f2a66e95b, miniServerSock6 was wrongly
used instead of miniServerSock6UlaGua
=> Fix listening on IPv6 LLA

upnp/src/gena/gena_device.c
Fix call to IN6_IS_ADDR_LINKLOCAL added by commit
4c584ea7f34bec09a5d3512a2c98d11616f76940. Currently it always returns
false and as a result, GENA subscribe on IPv6 LLA is always rejected
=> Fix CallStranger for IPv6 LLA

upnp/src/genlib/miniserver/miniserver.c
The media server gerbera is using libupnp. I'm using it with a Yamaha Network Player NP S303 which expects the server port to be 8200. Configuring gerbera using this port is only possible when I remove the requirement that the port be >= 49152.
This change removes that restriction. I think it is reasonable to assume that if a client requests a certain port number they know what they're doing. If they request port number 0, they get the default minimum port of 49152.
I have an alternative pull request which makes the change configurable.
=> Remove port >= 49152 restriction

upnp/src/api/upnpapi.c
The default 0 address gets encoded to :: and therefore fails the empty
check, causing us to try and initalize IPv6 when its not available.
=> macos: Do not set IPv6 address if not found.

upnp/src/api/upnpapi.c
Assume that getifaddrs is available even if it is not POSIX-compliant, this will simplify the code and, as a side effect, this allow pupnp to work on an interface that does not have an IPv4 address.
Fix #218
=> upnpapi.c: assume that getifaddrs is available

upnp/src/api/upnpapi.c
Fix build failure on windows added by commit aa0166c9a87a6f02632a0c55fb6174b6a1bf8289
=> upnpapi.c: fix windows build

upnp/src/api/upnpapi.c, upnp/src/genlib/miniserver/miniserver.c, upnp/src/ssdp/ssdp_ctrlpt.c, upnp/src/ssdp/ssdp_device.c
Don't set gIF_IPV4 if no IPv4 is found to keep the default value of '\0' otherwise SSDP will try to register IPv4 multicast with address 0.0.0.0 which will result in a runtime failure
=> upnp/src/api/upnpapi.c: don't set gIF_IPV4 if there is no IPv4

upnp/sample/common/tv_ctrlpt.c, upnp/sample/common/tv_ctrlpt.h, upnp/sample/linux/tv_combo_main.c, upnp/sample/linux/tv_ctrlpt_main.c
This is useful to test UPnP on specific interface (e.g. IPv6-only).
This was already possible on the device sample.
=> samples: allow the user to specify the control point interface

upnp/src/gena/gena_ctrlpt.c, upnp/src/inc/upnpapi.h
Use LOCAL_PORT_V6_ULA_GUA or LOCAL_PORT_V6 depending on the IPv6 address
=> Fix IPv6 GENA subscription

upnp/src/api/upnpapi.c
I got a crash on gerbera startup because at least one interface did not have `ifa_addr` set.
The reason is quite simple: they are the physical interfaces which are part of my channel 😄 
```
2: eth1: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc fq_codel master bond0 state UP group default qlen 1000
link/ether xx:xx:xx:xx:xx:xx brd ff:ff:ff:ff:ff:ff
3: eth0: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc fq_codel master bond0 state UP group default qlen 1000
link/ether xx:xx:xx:xx:xx:xx brd ff:ff:ff:ff:ff:ff
4: bond0: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
link/ether xx:xx:xx:xx:xx:xx brd ff:ff:ff:ff:ff:ff
```
=> Handle interfaces without address

upnp/src/api/upnpapi.c
Per getifaddrs documentation, the ifa_addr field of an ifaddrs structure
can be null. In a real world example, an entry may be provided for the
non-existent hardware address of a tunnel device. This behavior was
observed with the netlink based getifaddrs implementation in glibc.
=> Fix crash in UpnpGetIfInfo

upnp/generator/generator.c, upnp/inc/UpnpActionRequest.h, upnp/src/api/UpnpActionRequest.c, upnp/src/genlib/net/http/httpparser.c, upnp/src/genlib/net/http/webserver.c, upnp/src/inc/httpparser.h, upnp/src/soap/soap_device.c
This PR exposes unrecognized headers in the `UpnpActionRequest` interface
Api users might want to process some http headers that are not recognized by the pupnp http server. A similar behavior is already implemented for the upnp http io callbacks in the `FileInfo` interface.
=> Expose ExtraHeaderList in the ActionRequest interface

CMakeLists.txt, CMakeLists.txt.in, gtest/run_test, gtest/test_template.cpp, gtest/test_upnpapi.cpp
Download googletest from github with cmake into the project to simply
keep it up to date and to keep the project lean.
Just install with `cmake .` in `pupnp/`. It will download googletest to `pupnp/googletest-build`, `pupnp/googletest-src` and `pupnp/googletest-download` and build it:
pupnp$ cmake .  # there is a dot
pupnp$ make     # create the library
pupnp$ cd googletest-build
googletest-build$ make   # create googletest
This will create the different static linked programs in `pupnp/lib`. Use them to link your testsuites. Have a look at `pupnp/gtest/run_test`. It's a bash script. At first you should check the test environment by running the test_template.cpp. It must end without failures and output "PASSED":
gtest$ ./run_test test_template.cpp
Because the tests are compiled you can …
=> Added googletest and initial testsuites

.github/workflows/ccpp.yml, upnp/CMakeLists.txt, upnp/sample/CMakeLists.txt, upnp/test/CMakeLists.txt
I'm not sure if autotools just decided over your head to compile .c files as C, but I get errors with cpp-compiler. Easiest would be to just rename the files to .cpp or .cxx to let the system know what to do.
Related; #255
=> Changed to use cxx-compiler

Makefile.am
=> CMakeLists.txt missing in official 1.14.1 and 1.14.2 tarballs

CMakeLists.txt, ixml/CMakeLists.txt, upnp/CMakeLists.txt
Building shared libraries are not always possible as some embedded toolchains only support static linking so add options to build shared or static libraries and while at it install headers when building the static libraries
=> CMakeLists.txt: add UPNP_BUILD_{SHARED,STATIC} options

README.md
- Update broken links for UPnP IGD2
- Update ushare link to use a fork compatible with libupnp 1.14.x
- Add gmrender-resurrect, MPD and vlc
=> README.md: update libupnp users

upnp/inc/UpnpLog.h
Fix the following build failure:
```
In file included from /home/fabrice/br-test-pkg/bootlin-armv7m-uclibc/build/libupnp-8427b086494e7486864c96d38dfffdea2279956b/upnp/src/api/UpnpLog.cpp:6:
/home/fabrice/br-test-pkg/bootlin-armv7m-uclibc/build/libupnp-8427b086494e7486864c96d38dfffdea2279956b/upnp/inc/UpnpLog.h:142:17: error: ‘va_list’ has not been declared
142 |                 va_list argList);
|                 ^~~~~~~
```
=> upnp/inc/UpnpLog.h: include stdarg.h

.github/workflows/ccpp.yml
Today I cloned the sanitizer for cmake, and added all deactivated options to the test.
I wanted to split the options to one per line, but no matter what combination of "<option>\" and "<option> \" with next line indended or not, it always seemed that everthing after the first line get's swallowed. I'm not even sure if your flags get really added and not just set as vars after the configure, at least I saw something similar in the win build. An yes I used "run: |"
On win is openssl atm not buildable (give me a year or two for this), and on Mac it seems that the dev-files are not installed, so this is not tested there.
=> Added cmake sanitizer

upnp/src/genlib/miniserver/miniserver.c
When we implemented validation in Gerbera[0], I noticed that even if our
callback returns UPNP_E_BAD_HTTPMSG the request still get processed and
not dropped as expected.
Practically that means all hosts are valid if you have a validation
callback set :(
0. https://github.com/gerbera/gerbera/pull/2365
=> Dont call miniserver callbacks for failed hosts

upnp/src/threadutil/ThreadPool.h
This adjusts the ifdefs added in 421d5d2875a639b7c037ceadb8eec75d70d5346e (CC @ePirat).
In mingw headers, both `time.h` and `sys/time.h` define `struct timezone` and `_TIMEZONE_DEFINED` - however only one of them, `sys/time.h`, define `gettimeofday`. Thus, if `time.h` had been included before, we'd have `_TIMEZONE_DEFINED` defined, and we'd omit our own declaration of the `gettimeofday` function too, leading to calls to an undeclared function.
(If the actual `sys/time.h` header is included, its declaration of the `gettimeofday` function does conflict with both the declaration and the definition of upnp's `gettimeofday`, due to details like missing the `restrict` attribute on pointers. But that issue already existed and is unaffected by this patch.)
Since Clang 15 (which still is under …
=> windows: Avoid implicit declarations of gettimeofday()

.github/workflows/ccpp.yml
[Windows-2016 environment will be removed on March 15, 2022](https://github.com/actions/virtual-environments/issues/4312)
=> Remove windows-2016 build

upnp/src/genlib/miniserver/miniserver.c
I have fixed #342  for branch-1.14.x branch.
According to RFC 7230, port is optional in the Host.
If a port number is omitted, the entire value is now treated as a host name.
=> Fix #342: accept port number omission for branch-1.14.x branch

upnp/src/genlib/miniserver/miniserver.c
I have fixed #342  for master branch.
According to RFC 7230, port is optional in the Host.
If a port number is omitted, the entire value is now treated as a host name.
=> Fix #342: accept port number omission for master branch

upnp/src/genlib/miniserver/miniserver.c
`init_socket_stuff` was ignoring `inet_pton`'s return value causing
invalid IPs being seen as valid which caused bad calls to `bind` and
`listen` further in the code path.
Invalid `bind`s were frequents for interfaces providing only one IP
protocol version (IPv4 or v6). In those cases, `gIF_IPV4` or `gIF_IPV4`
were left to their default values (an empty string) causing `inet_pton`
to fail silently without aborting the socket opening and binding...
Refs #195
=> miniserver: Don't initialize sockets for invalid IPs

upnp/src/genlib/net/http/httpreadwrite.c
If for whatever reason the server replies without maxing out the buffer,
the code would end up doubling the buffer size nonetheless, which can
quickly cause malloc to fail, once we try to allocate 2^30 or more bytes
This was especially noticeable for large results.
Reported as https://code.videolan.org/videolan/vlc/-/issues/27173
=> http: RecvMessage: Fix potential allocation failure

upnp/src/threadutil/ThreadPool.c
`_get_timezone` & `_get_daylight` are only available when using UCRT
=> ThreadPool: Fix non UCRT builds

ixml/inc/posix_overwrites.h
The use of these fails as 2nd argument is the same as 4th argument. Reading the cpp_reference defintions of these, it can't be right
=> don't use strxxx_s on Windows

.github/workflows/cifuzz.yml
Add [CIFuzz](https://google.github.io/oss-fuzz/getting-started/continuous-integration/) workflow action to have fuzzers build and run on each PR.
This is a service offered by OSS-Fuzz where pupnp already runs. CIFuzz can help detect catch regressions and fuzzing build issues early, and has a variety of features (see the URL above). In the current PR the fuzzers gets build on a pull request and will run for 300 seconds.
Signed-off-by: David Korczynski <david@adalogics.com>
=> CI: Add CIFuzz action

upnp/src/api/upnpapi.c
Some initialization failures (such as failure in `UpnpGetIfInfo`) would leave resources like thread pools initialized. This change ensures if `UpnpInit2` fails, we call `UpnpFinish` before returning to clean up those resources.
To ensure `UpnpFinish` is effective in this case, we set `UpnpSdkInit` to 1 near the beginning of `UpnpInit2`.
=> Clean up after failed initialization.

upnp/src/genlib/miniserver/miniserver.c, upnp/src/inc/ssdplib.h, upnp/src/ssdp/ssdp_server.c
In case of a socket error, the socket was not removed from the select pool, causing future select() calls to return immediately, and readFromSSDPSocket() to be called just after on the failing socket. This was causing a high CPU load.
=> miniserver: fix busy loop on socket error

upnp/inc/UpnpInet.h, upnp/src/api/upnpapi.c
Not only is it unused, projects that pass -DNOCOMM under Windows end up failing compilation as more headers need to be included. Simpler to just not include.
=> UpnpInet: remove iphlpapi include

upnp/src/genlib/net/http/httpreadwrite.c
feesko is not supported on 32-bit Android older than API 24 [1]. Older SDKs would allow the call but the 64-bit off_t was not accurate. With the NDK26 the call is hidden in that case and calling fseeko() results in a compilation error.
[1] https://android.googlesource.com/platform/bionic/+/main/docs/32-bit-abi.md
=> disable fseeko usage on 32-bit Android older than API 24

upnp/inc/upnpconfig.h.cm
Fixes stuff like this:
```
[ 75%] Building C object upnp/CMakeFiles/upnp_static.dir/src/ssdp/ssdp_server.c.o
from /home/mroberto/programs/pupnp/maint/github-creator/upnp/src/inc/upnputil.h:40,
from /home/mroberto/programs/pupnp/maint/github-creator/upnp/src/inc/membuffer.h:40,
from /home/mroberto/programs/pupnp/maint/github-creator/upnp/src/inc/httpparser.h:41,
from /home/mroberto/programs/pupnp/maint/github-creator/upnp/src/inc/ssdplib.h:45,
from /home/mroberto/programs/pupnp/maint/github-creator/upnp/src/ssdp/ssdp_server.c:45:
/home/mroberto/programs/pupnp/maint/github-creator/upnp/inc/upnpconfig.h:42: warning: "UPNP_VERSION_STRING" redefined
42 | #define UPNP_VERSION_STRING "1.14.20"
| 
In file included from /home/mroberto/programs/pupnp/maint/github-creator/upnp/src/inc/config.h:36, …
```
=> Fix cmake redefinition warnings

upnp/inc/UpnpGlobal.h, upnp/src/gena/gena_device.c, upnp/src/genlib/net/http/httpreadwrite.c
Seems this PRIzu takes size_t, not unsigned long.
=> fix 32-bit format warnings

upnp/inc/upnptools.h, upnp/src/api/upnpapi.c, upnp/src/api/upnptools.c, upnp/src/threadutil/ThreadPool.c, upnp/src/threadutil/ThreadPool.h
avoids ThreadPoolAdd too many jobs: 100
in cases where heavy load is expected
Closes #449
=> Allow setting MaxJobsTotal for ThreadPools

ixml/src/ixmlparser.c
```
==1008254==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x507000000145 at pc 0x56086b6fe129 bp 0x7ffd0c0527d0 sp 0x7ffd0c0527c8 READ of size 1 at 0x507000000145 thread T0
#0 0x56086b6fe128 in Parser_getChar /home/mroberto/programs/pupnp/maint/github-creator/ixml/src/ixmlparser.c:999:35
#1 0x56086b6fcdb6 in Parser_copyToken /home/mroberto/programs/pupnp/maint/github-creator/ixml/src/ixmlparser.c:1163:7
#2 0x56086b6f7537 in Parser_processContent /home/mroberto/programs/pupnp/maint/github-creator/ixml/src/ixmlparser.c:1537:7
#3 0x56086b6f2818 in Parser_getNextNode /home/mroberto/programs/pupnp/maint/github-creator/ixml/src/ixmlparser.c:2067:9
#4 0x56086b6efa7f in Parser_parseDocument /home/mroberto/programs/pupnp/maint/github-creator/ixml/src/ixmlparser.c:2589:7
#5 …
```
=> ixmlparser.c: Fixes heap-buffer-overflow

upnp/src/api/upnpapi.c
Subscription packets are not properly handled on Windows due to a missing IPv4 netmask.
The following call would return 0 because the `gIF_IPV4_NETMASK` was not filled on Windows:
https://github.com/pupnp/pupnp/blob/48e7adc38b1fa071090b74723174c6a4c776fba4/upnp/src/gena/gena_device.c#L1252
Causing `gena_process_subscription_request` to return a `HTTP_PRECONDITION_FAILED` (412) to the user/subscriber:
https://github.com/pupnp/pupnp/blob/48e7adc38b1fa071090b74723174c6a4c776fba4/upnp/src/gena/gena_device.c#L1464
This fix creates the netmask using the `OnLinkPrefixLength` stored in the `uni_addr`.
Most likely related issues:
https://github.com/pupnp/pupnp/issues/379
https://github.com/pupnp/pupnp/pull/181
=> Fix subscription requests not working on Windows due to a missing netmask

upnp/src/ssdp/ssdp_device.c
It was possible for some uninitialized garbage to cause getaddrinfo() to fail on glibc 2.41, which would crash the client program.  Instead, zero the whole struct, and gracefully handle getaddrinfo() failures.
=> Improve SSDP initialization and error handling

upnp/src/ssdp/ssdp_device.c
Windows thinks argument 4 of `setsockopt()` is a `const char *`.  Add casts to avoid build errors with GCC.
Fixes: #477
=> ssdp_device.c: Fix missing casts in setsockopt()
