upnp/sample/common/tv_ctrlpt.c
upnp/sample/common/tv_device.c

- Don't ignore fgets() return value.

Fix compiler warning

---

ChangeLog
configure.ac

Enable IPv6 by default

---

configure.ac

Adjust library numbers for release

---

upnp/inc/upnpconfig.h.in

Add some more useful info to the header.

Expose BLOCKING_TCP_CONNECTIONS in upnpconfig.h

---

configure.ac
m4/ax_sys_largefile_sensitive.m4
upnp/inc/FileInfo.h
upnp/inc/upnpconfig.h.in
upnp/src/inc/sock.h

This fixes #52 and a few things that I noticed while working on this.

LFS support and minor cleanups

---

upnp/src/genlib/net/http/webserver.c

Crashes Gerbera when creating response for file request

Fix format string for ExtraHeaders

---

upnp/src/ssdp/ssdp_server.c
upnp/src/threadutil/LinkedList.c
upnp/src/threadutil/ThreadPool.c
upnp/src/threadutil/ThreadPool.h

There is no such define and its not defined in configure either so
checking it is useless.

Remove checks of __OSX__ define

---

ixml/inc/ixml.h
ixml/src/attr.c
ixml/src/element.c
ixml/src/inc/ixmlparser.h
ixml/src/ixmlmembuf.c
ixml/src/namedNodeMap.c
upnp/sample/common/tv_device.c
upnp/src/gena/gena_callback2.c
upnp/src/gena/gena_ctrlpt.c
upnp/src/genlib/miniserver/miniserver.c
upnp/src/genlib/net/http/httpparser.c
upnp/src/genlib/net/http/httpreadwrite.c
upnp/src/genlib/net/http/statcodes.c
upnp/src/genlib/net/http/webserver.c
upnp/src/genlib/net/uri/uri.c
upnp/src/genlib/util/strintmap.c
upnp/src/inc/gmtdate.h
upnp/src/inc/httpparser.h
upnp/src/inc/httpreadwrite.h
upnp/src/inc/miniserver.h
upnp/src/inc/parsetools.h
upnp/src/inc/server.h
upnp/src/inc/soaplib.h
upnp/src/inc/strintmap.h
upnp/src/inc/upnputil.h
upnp/src/inc/urlconfig.h
upnp/src/soap/soap_ctrlpt.c
upnp/src/soap/soap_device.c
upnp/src/ssdp/ssdp_ctrlpt.c
upnp/src/urlconfig/urlconfig.c

Those are inconsistently used and it is much cleaner to just write
it in the documentation like it is already done in most places in
the code.

Remove IN, OUT and INOUT defines

---

README.md

fix readme link to ChangeLog

---

README.md

It took me a while to get it build. Some trial and error, of looking up errors and installing the additional package.
This should give newcomers a better start by providing a minimal working set of instructions

docs(readme) update build instructions

---

configure.ac
ixml/Makefile.am
upnp/Makefile.am
upnp/inc/FileInfo.h
upnp/inc/UpnpGlobal.h
upnp/sample/common/sample_util.h
upnp/src/api/upnptools.c
upnp/src/gena/gena_ctrlpt.c
upnp/src/gena/gena_device.c
upnp/src/genlib/net/http/httpreadwrite.c
upnp/src/genlib/net/http/webserver.c
upnp/src/genlib/net/uri/uri.c
upnp/src/inc/inet_pton.h
upnp/src/inet_pton.c
upnp/src/soap/soap_device.c
upnp/src/ssdp/ssdp_ctrlpt.c
upnp/src/ssdp/ssdp_device.c
upnp/src/ssdp/ssdp_server.c
upnp/src/urlconfig/urlconfig.c

Fix Windows support when building with autotools under MSYS2.

---

upnp/Makefile.am
upnp/inc/UpnpGlobal.h
upnp/src/api/upnpdebug.c
upnp/src/threadutil/ThreadPool.c

Fix Windows support when building with MinGW.

---

upnp/src/api/upnpapi.c

Retrieve IPv6 ULA or GUA as well as prefix lengths for LLA and ULA/GUA
under BSD (i.e. with getifaddrs)

upnpapi.c: update IPv6 for BSD

---

upnp/src/api/upnpapi.c

Add comments to help a Windows-friendly user to fix the Windows parts

upnpapi.c: add comments for a Windows-friendly developer

---

CMakeLists.txt
CmDaB.cmake
upnp/CMakeLists.txt

I've added some stuff for older cmake-versions. With that debian buster should be also supported #217

Added compatibillity for Debian stable.

---

.github/workflows/ccpp.yml
CMakeLists.txt
ixml/CMakeLists.txt
upnp/CMakeLists.txt
upnp/test/CMakeLists.txt

Hi,
I've never looked at the numbers, just if they are there, but this should fix it. In addtion I droped the all uppcase from legacy cmake.
For the tests, they now should work with every situiation. I splitted the building in Release and Debug as the problem only exists in Release builds, so everything should work, or better the release part should fail, if it's not a local problem on my system.

Collected Work

---

upnp/src/ssdp/ssdp_ctrlpt.c

Also change from strcat() to memcpy(), should be slightly more
efficient.

Refactor redundant code

---

.github/workflows/ccpp.yml
upnp/CMakeLists.txt
upnp/sample/CMakeLists.txt
upnp/test/CMakeLists.txt

Reverts pupnp/pupnp#256
This was not meant to be merged right now, but later in the process.

Revert "Changed to use cxx-compiler"

---

.github/workflows/ccpp.yml

... and VSwhere (whatever that is)
and Choco (doesn't know either)
cmake-ninja's don't know the yml, so hopefully this works. At least the syntax check seems to pass.

Drop Ninja

---

.github/workflows/ccpp.yml
ixml/CMakeLists.txt

and readded the ixml-tests that went missing somewhen.

Release/Debug for Mac

---

upnp/sample/CMakeLists.txt

Don't assume that upnp_shared is available

upnp/sample/CMakeLists.txt: fix static build

---

upnp/src/genlib/net/http/httpreadwrite.c

(cherry picked from commit cc078412644513042c77258075752321208d4d5c)

Get rid of more alloca()

---

.github/workflows/clang-format.yml

It's just 3 files atm, but anyways.

Let cpp be checked also

---

CMakeLists.txt
upnp/CMakeLists.txt
upnp/inc/UpnpLog.h
upnp/src/api/UpnpLog.cpp
upnp/src/api/upnpapi.cpp

va_list cannot be used multiple times and causes a crash

Fix crash when using log callbacks

---

.github/workflows/ccpp.yml
gtest/test_template.cpp
ixml/inc/posix_overwrites.h
ixml/src/ixmlparser.c
upnp/inc/UpnpGlobal.h
upnp/sample/common/tv_ctrlpt.c
upnp/sample/common/tv_device.c
upnp/src/api/upnpapi.c
upnp/src/api/upnpdebug.c
upnp/src/api/upnptools.c
upnp/src/gena/gena_ctrlpt.c
upnp/src/gena/gena_device.c
upnp/src/genlib/miniserver/miniserver.c
upnp/src/genlib/net/http/httpparser.c
upnp/src/genlib/net/http/httpreadwrite.c
upnp/src/genlib/net/http/webserver.c
upnp/src/genlib/net/sock.c
upnp/src/genlib/net/uri/uri.c
upnp/src/genlib/util/util.c
upnp/src/ssdp/ssdp_ctrlpt.c
upnp/src/ssdp/ssdp_device.c
upnp/src/ssdp/ssdp_server.c
upnp/src/threadutil/ThreadPool.c
upnp/src/uuid/uuid.c
upnp/test/test_init.c

This should fix the remaining warnings.
This is still work in progress, but as I'm sometimes unsure (especially if the last one works as expected) I create this pr now to gather feedback.

Warnings 2

---

configure.ac
m4/ax_compiler_vendor.m4
m4/ax_prepend_flag.m4
m4/ax_require_defined.m4

Fixes autoconf build on some systems

Fixes autoconf build on some systems

---

upnp/src/soap/soap_device.c

Found when using https://play.google.com/store/apps/details?id=com.tjjang.upnptool

Headers do not have to be quoted

---

.gitignore
CMakeLists.txt
fuzzer/CMakeLists.txt
fuzzer/FuzzIxml.c
fuzzer/build.sh
ixml/src/ixmlparser.c

Should fix:
- https://issues.oss-fuzz.com/issues/42516908
- https://issues.oss-fuzz.com/issues/42516912

Int overflow 42516912

---

ixml/src/ixmlparser.c

Fixes https://issues.oss-fuzz.com/issues/42516907

ixmlparser.c: Fix for memory leak

---

.github/workflows/clang-format.yml
upnp/inc/ithread.h
upnp/sample/common/tv_device.c
upnp/src/api/upnpapi.c
upnp/src/genlib/net/http/httpreadwrite.c
upnp/src/inc/upnputil.h
upnp/src/ssdp/ssdp_server.c
upnp/test/test_url.c

Temporary fix for clang-format while the action is not updated to include clang-format 19.

Temporary fix for clang-format while the action is not updated

---

upnp/src/inc/ssdplib.h
upnp/src/ssdp/ssdp_device.c

Bind SSDP UDP response to 1900

---

upnp/src/ssdp/ssdp_device.c

Use `SO_REUSEPORT` with `SO_REUSEADDR`

Tweak ssdp_device
